version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - api
    user: developer

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
    - "8000"
    env_file:
      - ./api/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port ${API_PORT:-8000} --reload

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - client
      - api

networks:
  default:
    driver: bridge
